updated v0/cleanjobs
peviitor-ro/api pull request #307
Opened 2024-07-23 14:55 UTC by ale23yfm

Now, after deleting jobs from any company, it is shown the number of jobs deleted
closes #306

2024-07-23 19:50 UTC, sebiboga requested changes
we need to compute the number of jobs that specific company have before deleting
then delete
then show in response the count() we had before deletion

2024-07-24 13:04 UTC, ale23yfm commented
I have changed  this and now it counts the number of jobs that should be deleted, and after that it deletes those jobs

2024-07-24 16:30 UTC, ale23yfm commented
I forgot to add $qs to url and now it is working properly

2024-07-24 16:33 UTC, sebiboga approved these changes

2024-07-24 16:33 UTC, merged